# Generated by Django 5.2.1 on 2025-05-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(blank=True, default='', max_length=255)),
                ('location_type', models.CharField(choices=[('virtual', 'Virtual'), ('physical', 'Physical'), ('hybrid', 'Hybrid')], max_length=10)),
                ('venue', models.CharField(blank=True, default='', max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('description', models.TextField()),
                ('compensation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('language_preference', models.CharField(blank=True, default='', max_length=255)),
                ('special_requirements', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gigs',
            },
        ),
    ]
