# Generated by Django 5.2.1 on 2025-05-26 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('location_type', models.CharField(choices=[('virtual', 'Virtual'), ('physical', 'Physical'), ('hybrid', 'Hybrid')], max_length=10)),
                ('place', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('state_province', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('language_preference', models.CharField(blank=True, default='', max_length=255)),
                ('special_requirements', models.TextField(blank=True, default='')),
                ('compensation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expenses', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('receiving_applications', 'Receiving Applications'), ('agent_confirmed', 'Agent Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gigs',
            },
        ),
    ]
