# Generated by Django 5.2.1 on 2025-06-27 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_location_table'),
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='city',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='country',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='language_preference',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='place',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='special_requirements',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='state_province',
        ),
        migrations.AddField(
            model_name='gig',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gigs', to='core.location'),
        ),
        migrations.AddField(
            model_name='gig',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
