# Generated by Django 5.2.1 on 2025-07-11 12:51

import django.core.validators
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_remove_gig_city_remove_gig_country_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='expenses',
        ),
        migrations.AddField(
            model_name='gig',
            name='event_label',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='compensation',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='gig',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50, 'Must be atleast 50 characters long.')]),
        ),
    ]
