# Generated by Django 5.2.1 on 2025-07-26 15:41

import django.db.models.deletion
import gigs.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0007_gig_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_gigs', to=settings.AUTH_USER_MODEL, validators=[gigs.validators.validate_agent]),
        ),
        migrations.AlterField(
            model_name='gig',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL, validators=[gigs.validators.validate_client]),
        ),
    ]
