# Generated by Django 5.2.1 on 2025-07-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_alter_gig_agent_alter_gig_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('agent_confirmed', 'Agent Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
