# Generated by Django 5.2.1 on 2025-07-29 11:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_alter_gig_agent_alter_gig_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='compensation',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='gig',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('agent_confirmed', 'Agent Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
