# Generated by Django 5.2.1 on 2025-07-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0009_alter_gig_compensation_alter_gig_status'),
        ('gigs', '0009_alter_gig_status'),
    ]

    operations = [
    ]
