# Generated by Django 5.2.1 on 2025-08-02 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0011_alter_gig_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50, 'Must be at least 50 characters long')]),
        ),
    ]
