# Generated by Django 5.2.1 on 2025-05-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='has_agent_profile',
            new_name='is_agent',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='has_client_profile',
            new_name='is_client',
        ),
    ]
