# Generated by Django 5.2.1 on 2025-05-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_has_agent_profile_customuser_is_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='state_province',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
