# Generated by Django 5.2.1 on 2025-06-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_customuser_user_email_ci_uniqueness"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customuser",
            name="user_email_ci_uniqueness",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
