# Generated by Django 5.2.1 on 2025-07-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
    ]
