# Generated by Django 5.2.1 on 2025-07-02 14:57

from django.db import migrations, models


def combine_names(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    for custom_user in CustomUser.objects.all():
        custom_user.full_name = f"{custom_user.first_name} {custom_user.last_name}"
        custom_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_remove_customuser_full_name"),
    ]

    operations = [
        migrations.RunPython(combine_names),
        migrations.RemoveField(
            model_name="customuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
    ]
