# Generated by Django 5.2.1 on 2025-07-02 15:05

from django.db import migrations, models


def combine_names(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    for custom_user in CustomUser.objects.all():
        custom_user.full_name = f"{custom_user.first_name} {custom_user.last_name}"
        custom_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_customuser_first_name_customuser_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(combine_names),
        migrations.RemoveField(
            model_name="customuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
    ]
