# Generated by Django 5.2.1 on 2025-05-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state_province', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('city', 'state_province', 'country')},
            },
        ),
    ]
