# Generated by Django 5.2.1 on 2025-07-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_location_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='state_province',
            new_name='state_region',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'state_region', 'country')},
        ),
    ]
