# Generated by Django 5.2.1 on 2025-07-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_location_country_code_alter_location_state_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='country_code',
        ),
    ]
