# Generated by Django 5.2.1 on 2025-07-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_location_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state_region',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
