# Generated by Django 5.2.1 on 2025-10-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_location_state_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state_region',
            field=models.CharField(max_length=255),
        ),
    ]
